"""Добавление колонки History

Revision ID: 9f6b04afeedc
Revises: bef50fe6c67e
Create Date: 2025-01-28 22:39:14.847265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6b04afeedc'
down_revision = 'bef50fe6c67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('History',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('History',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
