"""Переименован столбец subject в IT

Revision ID: a2821e446c50
Revises: 238128c8d597
Create Date: 2025-01-28 21:10:26.782350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2821e446c50'
down_revision = '238128c8d597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IT', sa.String(length=80), nullable=True))
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('IT')

    # ### end Alembic commands ###
