"""Add History subject to Student model

Revision ID: bef50fe6c67e
Revises: 3e746642fe7f
Create Date: 2025-01-28 22:30:53.959936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef50fe6c67e'
down_revision = '3e746642fe7f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('History', sa.String(), nullable=False, default="Unknown"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('History')

    # ### end Alembic commands ###
