"""Добавлен столбец для корейского языка

Revision ID: ccb0bd12dfff
Revises: a2821e446c50
Create Date: 2025-01-28 21:37:41.525364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb0bd12dfff'
down_revision = 'a2821e446c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Korean', sa.Float(), nullable=True))
        batch_op.alter_column('IT',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('IT',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.drop_column('Korean')

    # ### end Alembic commands ###
